### ISSUE TITLE
Request timed out behind corporate proxy

### ISSUE THREAD

**Issue by mrmunch** [jenkinsci/octoperf-plugin#1]
I have a very similar issue to this one: https://github.com/Blazemeter/blazemeter-jenkins-plugin/issues/53
I'm behind a corporate proxy and always get a 
`Failed to connect to OctoPerf, please check your credentials. java.net.SocketTimeoutException: connect timed out`
(Credentials are good, I can login via app.octoperf.com)
This happens already on the "Configure Job" page (where I am supposed to choose a "Scenario")
I set my proxy in Manage Jenkins > Manage Plugins > Advanced.

It looks like OctoPerf Plugin does not use this proxy settings.

**Comment by jloisel** [comment]
Hi, We're using [Retrofit2](https://square.github.io/retrofit/) to perform HTTP calls. If you want proxy support, we can upgrade to use [OkHttp](http://square.github.io/okhttp/) client along with Retrofit2, which supports proxy settings.

I'm going to check how we can reuse Jenkins proxy settings from within the plugin.

**Comment by jloisel** [comment]
OK, found a way to take into account Jenkins proxy settings. Implementing the solution. I'll come back to you with a pre-built hpi to install on your local jenkins for testing.

**Comment by jloisel** [comment]
I've zipped the octoperf.hpi plugin, please [install it manually](https://jenkins.io/doc/book/managing/plugins/#advanced-installation):

[octoperf.zip](https://github.com/jenkinsci/octoperf-plugin/files/2620603/octoperf.zip)

It takes into account Jenkins proxy settings when setting up the http client to perform requests to OctoPerf.

**Comment by jloisel** [comment]
As a side note, [OctoPerf Enterprise-Edition](https://octoperf.com/enterprise/quick-start/) can entirely run behind your firewall / proxy in the case your company needs that all the data stays in-house. (typically banks)

**Comment by mrmunch** [comment]
Wow, what a quick reaction!
I installed your plugin and restarted Jenkins. 
Sadly, it still does not work - but this time with a different error message:

<details>
  <summary>Under "Test Credentials":</summary>
  <p>

```java
Login failed!
java.io.IOException: 
	at org.jenkinsci.plugins.octoperf.OctoperfCredentialImpl$DescriptorImpl.doTestLogin(OctoperfCredentialImpl.java:64)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:130)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:92)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:124)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

</p></details>

<details>
  <summary>In Job Configuration:</summary>
  <p>

```java
java.lang.NullPointerException
	at org.jenkinsci.plugins.octoperf.scenario.RetrofitScenarioService.getScenariosByProject(RetrofitScenarioService.java:36)
	at org.jenkinsci.plugins.octoperf.OctoperfBuilderDescriptor.doFillScenarioIdItems(OctoperfBuilderDescriptor.java:108)
	at org.jenkinsci.plugins.octoperf.OctoPerfTestStep$DescriptorImpl.doFillScenarioIdItems(OctoPerfTestStep.java:181)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:130)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:789)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:384)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:92)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:124)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

</p></details>

**Comment by jloisel** [comment]
After analyzing your logs:

- Login failed indicates either proxy settings or OctoPerf credentials are wrong,
- Job seems to fail because no scenario has been selected in job configuration prior to running it.

Can you please double check proxy settings and octoperf credentials to make sure those are correct? Let me know then.

**Comment by mrmunch** [comment]
Thank you for investigating!

I created a new OctoPerf account - but same result.
I successfully can load Plugin update data so it looks like my proxy settings are correct.

Regarding point 2: **not** only the job _execution_ fails - it already fails in the job _configuration_ page:
![jenkins-octoperf](https://user-images.githubusercontent.com/12833236/49146269-173a9700-f302-11e8-93b8-2fe1b87398ad.png)
(I get the same result also when I use a Pipeline Job and go to "Pipeline Syntax")

**Comment by mrmunch** [comment]
Some more details:
1. In my system settings I use the default server URL `https://api.octoperf.com`
2. I tried the following:
<details>
  <summary>Running this Code snippet works fine</summary>
  <p>

```java
        withEnv(["http_proxy=<MYPROXY>:<PORT>", "https_proxy=<MYPROXY>:<PORT>"]){
            sh "curl --header \"Authorization: Bearer <MY-API-KEY>\" -v -X POST https://api.octoperf.com/runtime/scenarios/run/<SCENARIO-ID>"
        }
```

</p></details>

<details>
  <summary>While this leads to "Authentication failed. java.net.SocketTimeoutException: connect timed out"</summary>
  <p>

```java
        withEnv(["http_proxy=<MYPROXY>:<PORT>", "https_proxy=<MYPROXY>:<PORT>"]){
            octoPerfTest credentialsId: '<MY-ID>', scenarioId: '<SCENARIO-ID>'
        }
```

</p></details>


3. One more thing: [In this documentation](https://doc.octoperf.com/integrations/ci/jenkins/#credentials) I see a *username* ("jsmith") in the screenshot - but I use an *e-mail-address* here (hope this is correct because I don't find a username in my OctoPerf account)

**Comment by jloisel** [comment]
Thanks for the info, i'm going to setup a local proxy a try from here to reproduce the issue and make a fix.

EDIT: your username is the email you used to register on OctoPerf.

**Comment by jloisel** [comment]
Tried with local proxy (mitm) and local server, it works fine. When I try with remote server (https://api.octoperf.com), it fails because my proxy certificate isn't registered as CA root on my machine.

Is the certificate of your proxy valid? try to access https://api.octoperf.com via the proxy.

**Comment by jloisel** [comment]
Proxy settings are working:

![selection_014](https://user-images.githubusercontent.com/3208716/49153454-0e53c080-f316-11e8-9c75-ff9285ee5398.png)

![selection_015](https://user-images.githubusercontent.com/3208716/49153487-275c7180-f316-11e8-8627-4cd77da67fcc.png)

This is on my local development server.

**Comment by jloisel** [comment]
I have released plugin 4.1.0 (which supports Jenkins proxy settings): https://repo.jenkins-ci.org/releases/org/jenkinsci/plugins/octoperf/4.1.0/octoperf-4.1.0.hpi

Give it a try (although I didn't change the code). also, try to test proxy on https://api.octoperf.com from [Jenkins Proxy Settings page](https://wiki.jenkins.io/display/JENKINS/JenkinsBehindProxy).

![selection_016](https://user-images.githubusercontent.com/3208716/49153844-32fc6800-f317-11e8-9b3d-9a0cafa07cca.png)

**Comment by mrmunch** [comment]
Oh interesting, for "https://api.octoperf.com" it fails (code 401) while "https://jenkins-ci.org" succeeded.

**Comment by jloisel** [comment]
That's fine you have a 401, because the API root "/" is not accessible without login. So, it seems like you have proper access to https://api.octoperf.com. Despite having installed my proxy root certificate, i'm getting:
```
Failed to connect to https://api.octoperf.com.

javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:450)
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.verifyHostName(SSLProtocolSocketFactory.java:257)
```

**Comment by mrmunch** [comment]
Let me know if you need more information from me!

**Comment by jloisel** [comment]
Is your proxy using authentication (username / password)?

I'm out of clue right now as it works fine on my local server. I'm struggling to make it work with api.octoperf.com as I cannot get the SSL certificate of the proxy to be trusted by the plugin.

**Comment by jloisel** [comment]
Can you try to test login again from credentials page?

**Comment by mrmunch** [comment]
Same result. I guess this line is new:
`Response{protocol=http/1.1, code=401, message=, url=https://api.octoperf.com/workspaces/member-of}`

**Comment by jloisel** [comment]
Make some progress, I have the 401 now too:

![selection_017](https://user-images.githubusercontent.com/3208716/49155127-760c0a80-f31a-11e8-97d7-8a2aec9af68d.png)

Which is good, it means my proxy ssl certificate is valid now! I have imported it using:

```
sudo keytool -import -trustcacerts -keystore /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/security/cacerts -storepass changeit -alias Root -import -file mitmproxy.crt
```

`mitmproxy.crt` is the CA root which generates the certificate of my proxy.

**Comment by jloisel** [comment]
I have successful login and able to list scenarios:

![selection_018](https://user-images.githubusercontent.com/3208716/49155570-8a043c00-f31b-11e8-8c4c-88b3a714c4ff.png)

So I confirm the plugin supports Proxy correctly now:

![selection_019](https://user-images.githubusercontent.com/3208716/49155605-a3a58380-f31b-11e8-84bb-e67630d5bde8.png)

The HTTP 401 I got several times before was because my password was wrong. Login success:

![selection_020](https://user-images.githubusercontent.com/3208716/49155640-c5066f80-f31b-11e8-9732-55cd7a99ed02.png)

So, from my understanding, there must be something wrong either in:

- your proxy settings,
- or your octoperf account username / password.

**Comment by jloisel** [comment]
Can also be a conflict with an existing plugin. Which plugins do you have installed? which versions of jenkins are you using?

**Comment by mrmunch** [comment]
Jenkins v2.153
Well, we currently have 181 plugins installed...

**Comment by jloisel** [comment]
If you get a 401 when testing login, then obviously you're not so far from making it work. Make sure to have the proper username and password and it should work. Once you have successfully login, basically it's done!

If you can test with a clean Jenkins install without any other plugin. It could help to understand if another plugin is conflicting with this one. although, I don't think there is a conflict, but I have really no other idea (since it works on my side).

**Comment by mrmunch** [comment]
One question: When you got the 401 code, did you receive it immediatly? When I click "Test Octoperf Credentials", the progress indicator is spinning for ~1min before I receive this error.

Just found another log (but only "INFO") in my jenkins log:
`Nov 28, 2018 3:20:48 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?`

**Comment by jloisel** [comment]
I'm receiving it almost immediately. The server usually answers very quickly. The fact it takes 1min seems to indicate you have a network timeout somehow. Is api.octoperf.com allowed by the proxy? 

Regarding Http/2, we're not explicitely using it, our api is just plain `http 1.1`. Which java version is running your Jenkins server? JDK 8 is required.

**Comment by mrmunch** [comment]
[The sh "curl" command mendetiond here](https://github.com/jenkinsci/octoperf-plugin/issues/1#issuecomment-442421204) works fine (code 200).
But when I remove the "withEnv" part, then I get code 504.
(The proxy in "withEnv" is the same like in Jenkins Plugin Manager -> Advanced Settings)

Jenkins is running on jdk8.

**Comment by jloisel** [comment]
Settings proxy via withEnv is almost the same (but with subtle difference): it sets the proxy on the Java JDK level. When setting proxy in Jenkins, i'm explicitely taking the proxy settings and applying them to the internal OkHttp client. OkHttp client otherwise takes the proxy settings from Java's ProxySelector (which in turn is sensitive to `http_proxy` and `https_proxy` settings).

Try to setup a local proxy, chained to your corporate proxy, to debug the requests going through. You should see the requests emitted by the plugin and the responses returned by your corporate proxy.

You can use tools like Fiddler or Mitm.

**Comment by mrmunch** [comment]
Thanks a lot for your support!
I'll try to fix my issue and provide a feedback when I succeeded.

**Comment by mrmunch** [comment]
Hi @jloisel 

after debugging, it it looks like the "[builder](https://github.com/jenkinsci/octoperf-plugin/blob/master/src/main/java/org/jenkinsci/plugins/octoperf/client/RetrofitClientService.java#L50)" client uses a proxy - but the very first call with the "[unauthenticatedClient](https://github.com/jenkinsci/octoperf-plugin/blob/master/src/main/java/org/jenkinsci/plugins/octoperf/client/RetrofitClientService.java#L41)" does NOT use a proxy - which leads to my issue.

**Comment by jloisel** [comment]
Thanks for the feedback. Let me investigate that, haven't thought about this when looking at the code.

EDIT: it was obviously working in my case because I had **both** with and without proxy access to the server.

**Comment by jloisel** [comment]
Please find the fixed version here: https://repo.jenkins-ci.org/releases/org/jenkinsci/plugins/octoperf/4.1.1/octoperf-4.1.1.hpi

You can install it manually as it won't be available in Jenkins updates until a few hours.

**Comment by mrmunch** [comment]
Works like a charm, thank you!
